### ISSUE TITLE
Settings & documentation missing instructions how to switch themes

### ISSUE THREAD

**Issue by DaveA-W** [dzsquared/high-color-queries#3]
After installing the extension to Azure Data Studio, the settings cog in the Extensions sidebar shows as Enabled, but no options available for switching themes.

How do we do this manually?

**Comment by DaveA-W** [comment]
Okay, found them as Workbench Color Themes in the main settings.  
Suggest worth a hat-tip in the README.md.

**Comment by dzsquared** [comment]
Switching themes is now addressed directly in the readme, thanks!
