### ISSUE TITLE
vsix file is missing

### ISSUE THREAD

**Issue by scottbass** [dzsquared/high-color-queries#4]
https://github.com/dzsquared/high-color-queries/releases/download/v0.0.4/hcq--high-color-queries--0.0.4.vsix

Page not found

**Comment by scottbass** [comment]
More info:  That link is from README.md, and is 404.  There is an extra "v" in "v0.0.4.
If you click Install from the Marketplace, you're taken to 
https://github.com/dzsquared/high-color-queries/releases/tag/0.0.4, which contains https://github.com/dzsquared/high-color-queries/releases/download/0.0.4/hcq--high-color-queries--0.0.4.vsix, which does work.

**Comment by dzsquared** [comment]
Thank you @scottbass!
