### ISSUE TITLE
some keywords are not colored

### ISSUE THREAD

**Issue by SteveSte** [dzsquared/high-color-queries#6]
I find HCQ (dark) quite clear and I'm using it all the day, thank you for it!
I have found that some keywords are not colored properly:

_keyword color_:   AS
_keyword2 color (dark HCQ)_: FOR, NOCHECK, ADD, CLUSTERED, NONCLUSTERED, UNIQUE, INDEX, MATCHED, CURSOR, .NODES
_function color:_  RIGHT, CAST

![immagine](https://user-images.githubusercontent.com/10895560/82468952-b12c6b80-9ac3-11ea-8e4e-fb73f232e776.png)

**Comment by dzsquared** [comment]
@SteveSte - the issue with syntax coloring was inherited from Azure Data Studio, which was inherited from VS Code and the mssql extension for VS Code.
The PR against that extension in VS Code has finally trickled down into Azure Data Studio v1.25 (December) and things should look better now.

thanks!

ref: https://github.com/microsoft/vscode-mssql/pull/1739

**Comment by SteveSte** [comment]
fine, thank you!
